FROM node:22-bookworm-slim AS node

FROM ruby:4.0.5-slim

WORKDIR /app

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential git libpq-dev postgresql-client && \
    rm -rf /var/lib/apt/lists/*

COPY --from=node /usr/local /usr/local

RUN rm -f /usr/local/bin/yarn /usr/local/bin/yarnpkg && corepack enable

COPY Gemfile ./
RUN bundle install

COPY . .

ENTRYPOINT ["./entrypoint.dev.sh"]
CMD ["bin/rails", "server", "-b", "0.0.0.0"]
