require "test_helper"

class BriefGenerationTest < ActionDispatch::IntegrationTest
  include ActiveJob::TestHelper

  test "an owner receives a completed immutable Brief generated by the server-side adapter" do
    adapter = FakeGeminiAdapter.new

    with_gemini_adapter(adapter) do
      unlock_workspace

      assert_enqueued_with(job: GenerateBriefJob) do
        post "/analysis_requests", params: { analysis_request: { source_url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ" } }
      end

      follow_redirect!
      assert_select "li", /queued/i

      perform_enqueued_jobs

      analysis_request = AnalysisRequest.last
      brief = analysis_request.brief

      assert_equal "completed", analysis_request.lifecycle_state
      assert_equal [ "https://www.youtube.com/watch?v=dQw4w9WgXcQ", "pl" ], adapter.received_arguments
      assert_equal [ "processing" ], adapter.lifecycle_states_seen
      assert_equal "Wykład o skupieniu", brief.source_title
      assert_equal "Kanał Wiedzy", brief.source_channel
      assert_equal Date.new(2026, 8, 1), brief.published_on
      assert_equal 1_245, brief.duration_seconds
      assert_equal "pl", brief.output_language
      assert_equal "## Nawyki pracy", brief.content_markdown
      assert_equal 5, brief.key_conclusions.length
      assert_equal "Nawyki pracy", brief.structured_content.fetch("sections").first.fetch("heading")
      assert_not brief.update(source_title: "Changed title")
      assert_equal "Wykład o skupieniu", brief.reload.source_title

      get "/workspace"

      assert_redirected_to "/workspace?brief_id=#{brief.id}"
      follow_redirect!

      assert_response :success
      assert_select "h1", "Wykład o skupieniu"
      assert_select "a[href=?]", workspace_path(brief_id: brief.id), "Open Brief"
      assert_select "a[href='https://www.youtube.com/watch?v=dQw4w9WgXcQ']"
      assert_select "h2", "Nawyki pracy"
      assert_select "li", "Zachowuj kontekst zadania."
      assert_select "p", /generated from the linked source/i
    end
  end

  test "an anonymous visitor cannot read a personal Brief" do
    analysis_request = AnalysisRequest.create!(source_url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ")
    brief = Brief.create!(
      analysis_request:,
      source_url: analysis_request.source_url,
      source_title: "Private Brief",
      source_channel: "Private Channel",
      published_on: Date.new(2026, 8, 1),
      duration_seconds: 60,
      output_language: "pl",
      content_markdown: "# Private",
      structured_content: { "sections" => [ { "heading" => "Private", "body" => "Private content." } ] },
      key_conclusions: [ "One.", "Two.", "Three.", "Four.", "Five." ]
    )

    get "/briefs/#{brief.id}"

    assert_redirected_to "/access"
  end

  test "a terminal source failure is shown without retrying" do
    adapter = FakeGeminiAdapter.new(GeminiAdapter::TerminalError.new("This video is private or inaccessible."))

    with_gemini_adapter(adapter) do
      unlock_workspace
      post "/analysis_requests", params: { analysis_request: { source_url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ" } }

      perform_enqueued_jobs

      analysis_request = AnalysisRequest.last
      assert_equal "failed", analysis_request.lifecycle_state
      assert_equal "This video is private or inaccessible.", analysis_request.failure_message
      assert_not analysis_request.recoverable_failure?
      assert_equal 0, analysis_request.automatic_retry_count
      assert_equal 1, adapter.attempts

      get "/workspace"

      assert_select "li", /failed/i
      assert_select "p", /private or inaccessible/i
      assert_select "p", /terminal and cannot be retried/i
      assert_select "form[action=?]", "/analysis_requests/#{analysis_request.id}/retry", count: 0
    end
  end

  test "an owner can retry after bounded automatic recovery is exhausted" do
    adapter = FakeGeminiAdapter.new(
      GeminiAdapter::RetryableError.new("Gemini quota is temporarily exhausted."),
      GeminiAdapter::RetryableError.new("Gemini quota is temporarily exhausted."),
      GeminiAdapter::RetryableError.new("Gemini quota is temporarily exhausted."),
      :success
    )

    with_gemini_adapter(adapter) do
      unlock_workspace
      post "/analysis_requests", params: { analysis_request: { source_url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ" } }

      3.times { perform_enqueued_jobs }

      analysis_request = AnalysisRequest.last
      assert_equal "failed", analysis_request.lifecycle_state
      assert analysis_request.recoverable_failure?
      assert_equal 2, analysis_request.automatic_retry_count

      get "/workspace"

      assert_select "p", /quota is temporarily exhausted/i
      assert_select "form[action=?]", "/analysis_requests/#{analysis_request.id}/retry"

      assert_enqueued_with(job: GenerateBriefJob) do
        post "/analysis_requests/#{analysis_request.id}/retry"
      end

      perform_enqueued_jobs

      assert_equal "completed", analysis_request.reload.lifecycle_state
      assert_equal 4, adapter.attempts
    end
  end

  private

  def unlock_workspace
    previous_password = ENV.fetch("OWNER_PASSWORD", nil)
    ENV["OWNER_PASSWORD"] = "a private test password"
    post "/access", params: { password: "a private test password" }
  ensure
    ENV["OWNER_PASSWORD"] = previous_password
  end

  def with_gemini_adapter(adapter)
    previous_adapter = Rails.configuration.x.gemini_adapter
    Rails.configuration.x.gemini_adapter = adapter
    yield
  ensure
    Rails.configuration.x.gemini_adapter = previous_adapter
  end

  class FakeGeminiAdapter
    attr_reader :received_arguments, :lifecycle_states_seen

    def initialize(*outcomes)
      @outcomes = outcomes.presence || [ :success ]
      @attempts = 0
    end

    attr_reader :attempts

    def analyze(source_url:, output_language:)
      @attempts += 1
      @received_arguments = [ source_url, output_language ]
      @lifecycle_states_seen = [ AnalysisRequest.find_by!(source_url:).lifecycle_state ]

      outcome = @outcomes.shift || :success
      raise outcome if outcome.is_a?(Exception)

      GeneratedBrief.new(
        source_url: source_url,
        source_title: "Wykład o skupieniu",
        source_channel: "Kanał Wiedzy",
        published_on: Date.new(2026, 8, 1),
        duration_seconds: 1_245,
        output_language: output_language,
        content_markdown: "## Nawyki pracy",
        structured_content: {
          "sections" => [
            { "heading" => "Nawyki pracy", "body" => "Mówca wyjaśnia, że krótkie bloki pracy pomagają utrzymać uwagę." }
          ]
        },
        key_conclusions: [
          "Zachowuj kontekst zadania.",
          "Ogranicz przełączanie uwagi.",
          "Planuj krótkie bloki pracy.",
          "Chroń czas bez powiadomień.",
          "Kończ jeden kontekst przed kolejnym."
        ]
      )
    end
  end
end
